services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cesoneemz
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: